hf_pg_dbt:
  outputs:
    dev:
      dbname: hellofresh
      host: postgres
      pass: hf_dbt_password
      port: 5432
      schema: public
      threads: 4
      type: postgres
      user: hf_dbt_user
  target: dev
